language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - sys-img-armeabi-v7a-android-27
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  - add-on
  - extra
  licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
cache:
  directories:
    - $HOME/.gradle
before_install:
- openssl aes-256-cbc -K $encrypted_9a063031b0d7_key -iv $encrypted_9a063031b0d7_iv
  -in keystore.jks.enc -out sign/keystore.jks -d
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: IRBf/+lCOPamiiGVQhyDg5AgvdgUyal5HNtDYVv6FdtvaH8n5/Tp40eTXOE4dJ2exK4+IRybatkmaPI7eOcLPRm3Fz9ZsawQwLSQNgNig0k7+iy3FdwVTPTSfq+pCQ+5ljLD2hAukT5Lejq+HmrSfnU3zFBxU4ekWQo8g41+EJDrZVL/xDE7vnpkohoeaPA0NDWr2Sl9vhmT+k8Whiuxi0yLpP8h7WXSQLP//p6TPiX+9ojNOIPJfDlypEWe9+hiASIRaC/XmIh6do15btCWUmj3+mwiR88Zzw3UKYVtotdYdjam2iFJx4mjEvDbJf634QLfcWzbnoqwgnHprIBDx+EhYRTPOZ/shIdyubEGanYU/9z9BLwWdejAqzua2bbf7GfPN10+mwxdfVUYOA9R6wO2NyFb/T40w5nKK4gaNn6N1RJFA9gSGpX+T6DVWGy9MzzJcVFhhuzub5dtBm4rKw1QhV4mpZFjz4F1Nbehkn0mHCj+fNYB/6XfEli4lv44TLKGjMJ9BvZjdop9NwAkar90moEx6IMSzwTlU/8q8J3fhvK5Mm49iZpMNXaB7nBv3XMTWH918Dl1JxaaJDN+udFawJoqR6/ZcOsu2Zuyi9sAZANdVuQDrWAZWUu/uN0tocnUJ3jb9VpKhJ6wJfCco/7nfbN5lGOYwIFQI6Bed44=
  file: app/build/outputs/apk/debug/Gank.IO.apk
  on:
    repo: sfsheng0322/RxGank
notifications:
  email:
  - sfsheng0322@126.com
