language: android
jdk: oraclejdk8
sudo: true
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - sys-img-armeabi-v7a-android-27
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  - add-on
  - extra
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- openssl aes-256-cbc -K $encrypted_9a063031b0d7_key -iv $encrypted_9a063031b0d7_iv
  -in keystore.jks.enc -out sign/keystore.jks -d
- gem install fir-cli
before_script:
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
    api_key:
      secure: clMUevnDIFVQj2sv8qdJz/H08Y6EBPMIyZQeYN5008wNoJu9NWokZO88dLi0t+qNhQ47J+D6YNCbsS8aFyFUELpOy+f/0xKqS7L1UMzIbDp/qHcPQThHck0oRl9iWkMJZ9iDdjob2p9yb77a15qKztxEKL+54tXRl6hBcymrY0Jmafpmn0nJtIu9WMBBWic85wQ716dQXjLd+ai/5ev8FXDD3gv9zQpM7wa7gpxsATizGTqG4SR+eJKv2RdbLgxdGbLpmuj1Ni7Ljq9T9g6PFmA/FQGpaMfTdt+j/p7Y2G2RYssvgiQUP1/6jR3F3nyxOCagmzV6LQHRtTvSYUuHPI0i3BC6ddzdh09QE/h4LrRCmDFbsITS5jRuL1rEGyDY+3X+/iBonAf4ec4vW3PA2zjErzdxuZz6g1x7JXqI5TS8yxSJmSwTG55LK8Nn5UUB9yLk7wXrjKpoAABTjXeVprjW9ez3vJB2o8faFbY+CIr3locSFfC0TEF6bDbKMyRIaK92Djfk1pZO6h6KKyRPWrQ1GoHsQPRKjHbpMZXrN0eoa0SoIUduk/b1vodFfKaZCb23YpNqMCvWNxjgxtotxaNr2XSRdU6SpAIyPm5cRGgHzzqpCz34JQp0R4UBvnKEu9W4HDhqcj4U93QHjpBdsmWxj919HxI+NKjDXtKV5sI=
    file: app/outputs/Gank.IO.apk
    skip_cleanup: true
    on:
      repo: sfsheng0322/RxGank
      tags: true
      all_branches: true
after_deploy:
- fir p app/outputs/Gank.IO.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
notifications:
  email:
  - sfsheng0322@126.com
