language: android
jdk: oraclejdk8
sudo: true
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.2
  - android-27
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-27
before_install:
- openssl aes-256-cbc -K $encrypted_9a063031b0d7_key -iv $encrypted_9a063031b0d7_iv
  -in keystore.jks.enc -out sign/keystore.jks -d
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: ofzSRZ+0yvQbymKFabUt/wuVee+hrZAHSi9vVdpD0F7lpN3psGrodz4U7ldNCaahyzSoqHdBjoP30Z+8+5dYRvIx05XOM6+57zsfZM83rNWJ0VNwlCISCuXxGpsYPWN/tJXRDQvwjGaUZ2pZzWcUTJvW9E7o1fH29Ow22feODo1t5Hae/uDPfZg79dKO5pJmfbz5dhFwZbNrIcDUYWhNJwurWgMXyt54z6mLnGI4gE19HJQMTJkBcX+s+dooIa1rPeWXnCkGdoJziCp0WeEFlVqrRq7Zabq5vxSPuaddFPlso5qUlQb8peP+dD1ZHbV/svUBxmrEuY0zKyPB4Rt9bkScBLlS6IUYKAo0pN9H6XstVOhcCm5rCYTtsy2RfO329S3UmNcDth5CDBv0Emrr8LpyXKSzTRRaqt55QaHIfvNDvBTA3s/eeiLNo4g982qPzoI/rvbLkb5GYc6dqUAAo7vIgzqthsWTg2dzd+F41qPcqEedb1c96U6ZmKPaCRXJdNBS74NTyNbQcrkVn7m+UgYbcaZBJEHZWcouqNQ4a17NJaTeIsrYZyb/GZP9S8GpphtgwmL9+4wlSyQepAheqOcCIm9RLEdDFg3HprBu+NX5AkKMBAcjfNV3VCtNH+OM62PBUSjAk2EU5thCUnrC6AJV7f7t8C4igk8PN00ca1s=
  file: app/build/outputs/apk/debug/Gank.IO.apk
  on:
    repo: sfsheng0322/RxGank
notifications:
  email:
  - sfsheng0322@126.com
